name: Tag and Push

on:
  pull_request:

# env:
# # git credentials
#   GIT_TOKEN: ${{ secrets.ghdevexservacctjenkins }}

jobs:
  tagAndPush:
    name: tag and push new image
    runs-on: ubuntu-latest
    if: endsWith(${{github.base_ref}},"master")
    steps:
    - name: WaitOnDeploy
      uses: lewagon/wait-on-check-action@v0.1
      with:
        # ref: master
        ref: main
        check-name: deployAndValidate
        wait-interval: 20
    - name: checkout-master
      uses: actions/checkout@v2
      # with:
      #   token: ${{ env.GIT_TOKEN }}
    - name: tagAndPush
      run: |
        echo "scripts/deliver.py -lll tag-repo"
        echo "WRITING THE TAGS BACK TO THE REPO"
        # git push --tags `echo $GITHUB_SERVER_URL | sed "s/github/ghdevexservacctjenkins:$GIT_TOKEN@github/"`
        git push --tags `echo $GITHUB_SERVER_URL`